sudo: required

language: go
go: "1.10"

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - IMAGE=lagoonplatform/installer
    - DEP_VERSION="0.4.1"

jobs:
  include:
      - stage: "Install DEP"	
        before_install:
          - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
          - chmod +x $GOPATH/bin/dep	
          - cd go        
        install:
          - dep ensure
         
        script: 
          - go test -v $( go list ./...)
          - cd ..
        before_deploy:  
          - docker run --rm -v "$PWD/go":/go/src/installer -w /go/src/installer iron/go:dev go build -o installer
          - docker build -f Dockerfile -t $IMAGE:$COMMIT .
          - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
          - docker tag $IMAGE:$COMMIT $DOCKER_REPO/$IMAGE:$TAG
          - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          - docker push $DOCKER_REPO/$IMAGE:$TAG
        if: type = push AND env(DOCKER_REPO) != "" AND env(DOCKER_USERNAME) != ""
